#!/usr/bin/python3
# SPDX-License-Identifier: BSD-3-Clause
# Copyright(c) 2018 Nippon Telegraph and Telephone Corporation

import sys

from spp_ctl import main


if __name__ == "__main__":
    sys.exit(main())
