topo_sec_colors:
    val: ["blue", "green", "orange", "chocolate", "black", "cyan3",
          "green3", "indianred", "lawngreen", "limegreen"]
    desc: Line colors for secondary processes
topo_port_colors:
    val: {"phy": "white", "ring": "yellow", "vhost": "antiquewhite",
          "tap": "cornsilk", "nullpmd": "cyan"}
    desc: Port colors
